import { useState, useMemo, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import Card from '../UI/Card';
import { formatBDT, formatBDTShort, formatNumber, formatPercent, formatDate } from '../../utils/formatters';
import { computeHotProducts, computeColdProducts } from '../../utils/productIntelligence';
import { computeWeekOverWeekGrowth, computeMTDComparison } from '../../utils/analytics';

function generateReportText(data) {
  const { report, dateStr, wow, mtd, hot, cold } = data;
  if (!report) return '';

  const lines = [];

  lines.push('\u{1F4CB} ANZAAR ISLAMIC LIFESTYLE');
  lines.push(`\u{1F4C5} Daily Sales Report \u{2014} ${dateStr}`);
  lines.push('');
  lines.push('\u{2501}'.repeat(36));
  lines.push('\u{1F4CA} Summary');
  lines.push('\u{2501}'.repeat(36));
  lines.push(`\u{2022} Total Orders: ${formatNumber(report.totalOrder)} (${formatNumber(report.regularOrder)} Regular + ${formatNumber(report.customizeOrder)} Custom)`);
  lines.push(`\u{2022} Total Products: ${formatNumber(report.totalProduct)}`);
  lines.push(`\u{2022} Order Value: ${formatBDT(report.totalOrderValue)}`);
  lines.push(`\u{2022} Advance: ${formatBDT(report.totalAdvance)} (${formatPercent(report.advanceRate)})`);
  lines.push(`\u{2022} Outstanding: ${formatBDT(report.outstandingAmount || 0)}`);

  if (wow) {
    lines.push('');
    lines.push('\u{2501}'.repeat(36));
    lines.push('\u{1F4C8} Week Comparison');
    lines.push('\u{2501}'.repeat(36));
    lines.push(`\u{2022} This Week: ${formatNumber(wow.currentOrders)} orders (${formatBDTShort(wow.currentValue)})`);
    lines.push(`\u{2022} Last Week: ${formatNumber(wow.previousOrders)} orders (${formatBDTShort(wow.previousValue)})`);
    const icon = wow.orderGrowth > 0 ? '\u{1F4C8}' : wow.orderGrowth < 0 ? '\u{1F4C9}' : '\u{27A1}';
    lines.push(`\u{2022} Growth: ${wow.orderGrowth > 0 ? '+' : ''}${wow.orderGrowth}% ${icon}`);
  }

  if (mtd) {
    lines.push('');
    lines.push('\u{2501}'.repeat(36));
    lines.push('\u{1F4C5} Month to Date');
    lines.push('\u{2501}'.repeat(36));
    lines.push(`\u{2022} This Month: ${formatNumber(mtd.mtd.orders)} orders (${formatBDTShort(mtd.mtd.value)})`);
    lines.push(`\u{2022} Last Month: ${formatNumber(mtd.lastMonth.orders)} orders (${formatBDTShort(mtd.lastMonth.value)})`);
    lines.push(`\u{2022} Growth: ${mtd.orderGrowth > 0 ? '+' : ''}${mtd.orderGrowth}%`);
  }

  if (report.products && report.products.length > 0) {
    lines.push('');
    lines.push('\u{2501}'.repeat(36));
    lines.push('\u{1F525} Top Products Today');
    lines.push('\u{2501}'.repeat(36));
    const sorted = [...report.products].sort((a, b) => b.quantity - a.quantity).slice(0, 5);
    sorted.forEach((p, i) => {
      lines.push(`${i + 1}. ${p.name} \u{2014} ${p.quantity} pcs`);
    });
  }

  if (hot.length > 0) {
    lines.push('');
    lines.push('\u{2501}'.repeat(36));
    lines.push('\u{1F525} Need Stock');
    lines.push('\u{2501}'.repeat(36));
    hot.slice(0, 5).forEach(p => {
      lines.push(`\u{2022} ${p.name} \u{2014} ${formatNumber(p.qty7)} sold in 7 days`);
    });
  }

  if (cold.length > 0) {
    lines.push('');
    lines.push('\u{2501}'.repeat(36));
    lines.push('\u{2744} Don\u2019t Restock');
    lines.push('\u{2501}'.repeat(36));
    cold.slice(0, 5).forEach(p => {
      const days = p.daysSinceLastSale === Infinity ? 'never' : `${p.daysSinceLastSale} days`;
      lines.push(`\u{2022} ${p.name} \u{2014} no sale in ${days}`);
    });
  }

  lines.push('');
  lines.push('\u{2501}'.repeat(36));
  lines.push('Generated by Anzaar Sales Dashboard');
  lines.push(`\u{1F517} sales-report-lime.vercel.app`);

  return lines.join('\n');
}

export default function DailySummaryReport({ latestReport, reports, products }) {
  const [showModal, setShowModal] = useState(false);
  const [copied, setCopied] = useState(false);

  const dateStr = useMemo(() => latestReport ? formatDate(latestReport.dateString) : '', [latestReport]);
  const wow = useMemo(() => computeWeekOverWeekGrowth(reports || []), [reports]);
  const mtd = useMemo(() => computeMTDComparison(reports || []), [reports]);
  const hot = useMemo(() => computeHotProducts(products, reports, 5), [products, reports]);
  const cold = useMemo(() => computeColdProducts(products, reports, 5), [products, reports]);

  const reportText = useMemo(() => generateReportText({
    report: latestReport,
    dateStr,
    wow,
    mtd,
    hot,
    cold,
  }), [latestReport, dateStr, wow, mtd, hot, cold]);

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(reportText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      const ta = document.createElement('textarea');
      ta.value = reportText;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }, [reportText]);

  if (!latestReport) return null;

  return (
    <>
      <button
        onClick={() => setShowModal(true)}
        className="btn-primary text-sm flex items-center gap-2"
      >
        <span>📋</span>
        <span>Share Report</span>
      </button>

      {showModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm" onClick={() => setShowModal(false)}>
          <div className="bg-bg-card border border-border rounded-2xl w-full max-w-lg max-h-[80vh] flex flex-col shadow-2xl" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between p-5 border-b border-border">
              <div>
                <h3 className="font-display text-lg text-text-primary">Daily Summary</h3>
                <p className="text-xs text-text-muted mt-0.5">{dateStr}</p>
              </div>
              <button
                onClick={() => setShowModal(false)}
                className="text-text-muted hover:text-text-primary text-lg leading-none p-1"
              >
                ✕
              </button>
            </div>

            <div className="flex-1 overflow-y-auto p-5">
              <pre className="text-xs leading-relaxed text-text-primary whitespace-pre-wrap font-mono bg-bg-elevated/30 p-4 rounded-xl border border-border">
                {reportText}
              </pre>
            </div>

            <div className="flex items-center gap-3 p-5 border-t border-border">
              <button
                onClick={handleCopy}
                className={`btn-primary flex-1 text-sm flex items-center justify-center gap-2 ${copied ? 'bg-accent-teal' : ''}`}
              >
                {copied ? (
                  <>✓ Copied!</>
                ) : (
                  <>📋 Copy to Clipboard</>
                )}
              </button>
              <button
                onClick={() => setShowModal(false)}
                className="btn-secondary text-sm"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
